app = "backend-lingering-pine-7093"  # your Fly.io app name
primary_region = "sea"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[env]
  # optional: if you want a fallback
  PORT = "8080"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
